### PR TITLE
Updated SMA demo; more end-to-end steps

### PR DESCRIPTION
**Pull request by enze-chen**
This is a great end-to-end demo of the UI that Carena made. I mostly made sure the code and figures corresponded to newest version of the platform/Python. Also added some more details in Reports/Design.

### CODE REVIEW

**Comment by jling11** [comment]
I must have a different version of some library than you @enze-chen , because that doesn't run for me.

$ python test.py
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    data = data.rename({h:'PROPERTY: '+ h for h in list(data.columns)}, axis='columns')
 ...
TypeError: rename() got an unexpected keyword argument "axis"

**Comment by enze-chen** [comment]
Good call. Added backwards compatibility, but then had to change the subsequent line. Also added a comment to upgrade pandas with pip. Could you verify again?

**Comment by maxhutch** [comment]
@jling11 can you try installing the dependency versions with `pip install -U -r requirements.txt`?  We have automated tests here, so I want to figure out why they passed by you experienced an error.

**Comment by jling11** [comment]
Works for me now--thanks Enze!

**Comment by maxhutch** [comment]
The images/screenshots for steps 3 and 4 don't seem particularly instructive, and the image below "With ML configured, models will start to train in the background (blue bars appear). After waiting for a short while, the training will complete and we can see our new ML model!" is a bit confusing: is the matrix view the model?  I'd have expected a screenshot of them predict page or model reports.

**Review by jling11 — DISMISSED** [review]
lgtm

**Comment by enze-chen** [comment]
@maxhutch thanks for the feedback! Some of those were carried over from the old version. I agree with your sentiment and removed them.

**Review by maxhutch — CHANGES_REQUESTED** [review]
If they are no longer referenced, can we remove the image files as well?

**Comment by enze-chen** [comment]
Agreed, and done!

**Review by maxhutch — APPROVED** [review]

**Comment by enze-chen** [comment]
Can this PR be merged?

**Comment by maxhutch** [comment]
Yeah.  Sorry, I thought you had merge permissions.

**Pull request merged**
