### PR TITLE
Enze/update search

### PR DESCRIPTION
**Pull request by enze-chen**
Updated the two query tutorials; pretty sure there are no conflicts with other PR.

Can't figure out what the error is referring to.

### CODE REVIEW

**Comment by maxhutch** [comment]
Those failures are very strange.  It might be a transient issue in a package that we depend on.  I'm going to just re-trigger periodically to see if it goes away (the `kick it until it works` strategy); we can dive in if it doesn't.

**Comment by maxhutch** [comment]
Looks like kicking it worked.

**Comment by maxhutch** [comment]
@enze-chen can you update this with the `master` branch before I review?

**Comment by enze-chen** [comment]
👍 merged in master.

**Comment by maxhutch** [comment]
Could you add the `... ommitted for space ...` messages at the end of the truncated prints?  Otherwise, looks great!

**Review by maxhutch — APPROVED** [review]

**Pull request merged**
