### PR TITLE
updated tutorial notebooks

### PR DESCRIPTION
**Pull request by carenac**
updated API tutorial notebooks (found [here](https://citrination.org/learn/api-examples/)) to be compatible with newest version of the python citrination client

### CODE REVIEW

**Comment by maxhutch** [comment]
Which version?  Could you add a [requirements.txt](https://pip.readthedocs.io/en/1.1/requirements.html) file ([example](https://github.com/CitrineInformatics/python-citrination-client/blob/develop/requirements.txt))?

**Comment by carenac** [comment]
added updated requirements. Also updates print statements to be compatible with python 3 (https://github.com/CitrineInformatics/learn-citrination/issues)

**Comment by maxhutch** [comment]
The 6 notebooks that this covers all run for me with python3.  @carenac , have you tested these on python2 by any chance?

**Comment by carenac** [comment]
@maxhutch confirmed working with py2

**Review by maxhutch — APPROVED** [review]
I re-ran with python3, and it still works.

**Pull request merged**
