### PR TITLE
Suggested edits to TsneDemo

### PR DESCRIPTION
**Pull request by maxhutch**
From https://github.com/CitrineInformatics/learn-citrination/pull/36

### CODE REVIEW

**Comment by mgdotdev** [comment]
That looks better :D

**Review by ahl389 — APPROVED** [review]

**Comment by maxhutch** [comment]
Thanks @1mikegrn !

**Comment by mgdotdev** [comment]
Happy to contribute :)

**Comment by mgdotdev** [comment]
And if y'all have any more todo's you'd be willing to throw out, I'd be happy to take a crack at some of them. I actually sent in a few applications for some of the open positions at Citrine recently; figure the best way to establish a rapport would be to just jump in and start contributing to the stack.

**Pull request merged**
