### PR TITLE
updated UI tutorials with Groups information

### PR DESCRIPTION
**Pull request by enze-chen**
Small update: Only updated the markdown files to give more visibility into sharing privileges, and the difference between Teams and Groups.

Small addition: Also clarified what "Group By Key" means in ML config.

### CODE REVIEW

**Review by maxhutch — COMMENTED** [review]
The group by bit looks good.  I'm not really in a position to review groups/teams.  @nequalszero @sparadiso could either of you put eyes on that?

**Review by sparadiso — DISMISSED** [review]
The content looks fine to me. I am curious if we actually need to document _both_ Teams and Groups. I thought that Teams was the official feature and Groups is the underlying mechanism that was exposed to users when we didn't have a user-friendly alternative (read: Teams).

**Comment by enze-chen** [comment]
@maxhutch CI can't find Python 3.4 for some reason. Maybe it's trying to use the most recent version of Conda, which doesn't support 3.4? Should I remove it from the list of Python kernels?

**Comment by enze-chen** [comment]
Any thoughts on the above about removing 3.4 from CI? This doesn't prevent `citrination_client` from supporting Python 3.4 does it?

**Comment by maxhutch** [comment]
@enze-chen yeah, let's remove it.  We should also communicate that, while the code may work, we are not testing it against 3.4.  We should not claim to support something that we can't test.

**Comment by enze-chen** [comment]
@maxhutch Done, and added a comment to the main README.md.

**Review by maxhutch — APPROVED** [review]

**Pull request merged**
