### PR TITLE
Documenting swap_kernel and test_notebooks

### PR DESCRIPTION
**Pull request by maxhutch**
Going back and adding documentation.

### CODE REVIEW

**Comment by enze-chen** [comment]
Hi Max, thanks for getting started on this. All the comments you added look good to me. I was wondering if it was possible / appropriate to add a `ci/README.md` or comments somewhere for the workflow? Basically once you said, "look at `.travis.yml` which references the other two files" it all made sense, but at first glance I wouldn't realize that's where I would need to start or add more notebooks to be tested.

**Review by enze-chen — CHANGES_REQUESTED** [review]
Hi Max, thanks for getting started on this. All the comments you added look good to me. I was wondering if it was possible / appropriate to add a `ci/README.md` or comments somewhere for the workflow? Or a link to where I can see more reference on this concept.

Basically once you said, "look at `.travis.yml` which references the other two files" it all made sense, but at first glance I wouldn't realize that's where I would need to start or to add more notebooks to be tested.

**Comment by maxhutch** [comment]
Great idea @enze-chen .  I added it.

**Comment by enze-chen** [comment]
lgtm @maxhutch. Really helpful links and instructions. :+1:

**Review by enze-chen — APPROVED** [review]

**Pull request merged**
